include         windows.inc
include         gdi32.inc
include         user32.inc
include         kernel32.inc
include         Msimg32.inc
include         msvcrt.inc
include         gdiplus.inc

includelib      gdi32.lib
includelib      user32.lib
includelib      kernel32.lib
includelib      Msimg32.lib
includelib      msvcrt.lib
includelib      gdiplus.lib
includelib     windows.lib

;sound
;windows 的 inc文件和lib文件同名
include winmm.inc
includelib Winmm.lib

