public player         
public bullet             
public targets

;zzl own
public button_play      
public button_2p_play  
public button_start      
public button_load
public button_back      
public button_exit    
public button_retry
public button_pause   
public backGround       
public object_DC        
public digitals_DC
public playerList
public playerList2

public hInstance       
public hWinMain      
public hWinMain2      
public hDCBack         
public hDCGame         
public hDCGame2         
public hDCObj1        
public dwNowBack     

public flag_jump               
public flag_movleft          
public flag_movright           
public stdtime_jump          
public time_jump              
public stdtime_mov             
public time_mov             
public cur_interface     

public target_number       
public speed
public base_speed
public speed_acc_time
public speed_dec_time


public object1H   
public object1W      
public object_move_v  
public POSCNT
public change_two_status_cnt



;==================== 共生模式 ===========================

public playerOne
public targetsOne
public target_number_one
public bulletOne

public playerTwo
public targetsTwo
public target_number_two
public bulletTwo

;==================== 共生模式 ===========================
