extrn player:Subject         
extrn bullet:Subject             
extrn targets

;zzl own
extrn button_play:Button      
extrn button_start:Button      
extrn button_back:Button      
extrn button_exit:Button       
extrn backGround:BackGround       
extrn object_DC:Object_DC        

extrn hInstance       
extrn hWinMain      
extrn hDCBack         
extrn hDCGame         
extrn hDCObj1        
extrn dwNowBack      

extrn flag_jump               
extrn flag_movleft            
extrn flag_movright           
extrn stdtime_jump            
extrn time_jump              
extrn stdtime_mov             
extrn time_mov             
extrn cur_interface     

extrn target_number       
extrn speed     