EXE = main.exe 
OBJS = main.obj ldf.obj sst.obj lja.obj
RES = main.res 

LINK_FLAGS = /subsystem:console
ML_FLAGS = /c /coff

$(EXE):$(OBJS) $(RES)
		Link $(LINK_FLAGS) $(OBJS) $(RES)

.asm.obj:
		ml $(ML_FLAGS) $<

.rc.res:
		rc $<

clean:
	del *.obj
	del *.res

ldf:
	ml $(ML_FLAGS) ldf.asm
	link $(LINK_FLAGS) ldf.obj

lja:
	ml $(ML_FLAGS) lja.asm
	link $(LINK_FLAGS) lja.obj

sst:
	ml $(ML_FLAGS) sst.asm
	link $(LINK_FLAGS) sst.obj