EXE = main.exe 
OBJS = main.obj ldf.obj sst.obj lja.obj
RES = main.res 

LINK_FLAGS = /subsystem:console
ML_FLAGS = /c /coff

$(EXE):$(OBJS) $(RES)
		Link $(LINK_FLAGS) $(OBJS) $(RES)

.asm.obj:
		ml $(ML_FLAGS) $<

.rc.res:
		rc $<

clean:
	del *.obj
	del *.res 